# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ability1', models.CharField(max_length=32)),
                ('abdesc1', models.CharField(max_length=255)),
                ('ability2', models.CharField(max_length=32)),
                ('abdesc2', models.CharField(max_length=255)),
                ('ability3', models.CharField(max_length=32)),
                ('abdesc3', models.CharField(max_length=255)),
                ('ability4', models.CharField(max_length=32)),
                ('abdesc4', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('tips', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField()),
                ('tips', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_maining', models.ManyToManyField(default=None, related_name='main_roles', to='login_registration.User')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='roles',
            field=models.ManyToManyField(default=None, related_name='rec_heros', to='core.Role'),
        ),
    ]
