# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hero_users_maining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='abdesc1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='abdesc2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='abdesc3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='abdesc4',
            field=models.TextField(),
        ),
    ]
