# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='master',
            field=models.IntegerField(default=0),
        ),
    ]
